name: Deploy to AWS Lightsail Container Service

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: eu-north-1                   # Set this to your preferred AWS region
  ECR_REPOSITORY: enki-webapp              # Set this to your Amazon ECR repository name
  LIGHTSAIL_SERVICE_NAME: enki-webapp-lightsail-container-service-1 # Set this to your AWS Lightsail container service name
  LIGHTSAIL_DEPLOYMENT_NAME: enki-webapp-lightsail-container # Set this to your AWS Lightsail container deployment name

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          echo ${{ secrets.AWS_SECRET_ACCESS_KEY }} | docker login --username AWS --password-stdin $ECR_REGISTRY
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "image=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_ENV

      - name: Update Lightsail Container Service
        run: |
          aws lightsail create-container-service-deployment \
            --service-name ${{ env.LIGHTSAIL_SERVICE_NAME }} \
            --containers "name=web,image=${{ env.image }},ports={\"5000\":\"HTTP\"}" \
            --public-endpoint "containerName=web,containerPort=5000,healthCheckPath='/'" \
            --region ${{ env.AWS_REGION }}
